[package]
name = "loops_for_2"
version = "0.1.0"
authors = ["basicdays <info@basicdays.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
