[package]
name = "ch_15_6_ref_cycles"
version = "0.1.0"
authors = ["basicdays <info@basicdays.com>"]
edition = "2018"
default-run = "ch_15_6_ref_cycles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
